djclub/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

#topic
urlpatterns = patterns('djclub.app.views.topic',
    url(r'^$', 'index'),
    url(r'^add/topic/$', 'add', name='topicadd'),
    url(r'^topic/(?P<topic_id>[\d]+)/$', 'view', name="topicview"),
    url(r'^topic/(?P<topic_id>[\d]+)/edit/$', 'edit', name="topicedit"),
    url(r'^topic/(?P<topic_id>[\d]+)/fav/$', 'fav', name="topicfav"),
    url(r'^topic/(?P<topic_id>[\d]+)/delete/$', 'delete', name="topicdel"),
    url(r'^topic/(?P<topic_id>[\d]+)/vote/$', 'vote', name="topicvote"),
)

#node
urlpatterns += patterns('djclub.app.views.node',
	url(r'^add/node/$', 'add', name='nodeadd'),
    url(r'^node/(?P<node_site>[\w\d\-]+)/?$', 'show'),
    url(r'^node/(?P<node_site>[\w\d\-]+)/(?P<page>[\d]+)/?$', 'show'),
    url(r'^node/edit/(?P<node_name>[\w\d\-]+)/$', 'edit', name='nodedit'),
)

#account
urlpatterns += patterns('djclub.app.views.account',
    url(r'^account/login/$', 'login', name='login'),
    url(r'^account/logout/$', 'logout', name='logout'),
    url(r'^account/register/$', 'register', name='register'),
    url(r'^account/register/~(?P<inviter>[\w\d]+)/?$', 'register', name='register'),
    url(r'^member/(?P<user_name>[\w\-\d]+)/?$', 'usercenter'),
    url(r'^settings/?$', 'setting'),
    url(r'^users/?$', 'users', name='users'),
    url(r'^top/?$', 'top', name='top'),
    url(r'^favorites/$', 'favorites', name='favorites'),
    url(r'^times/$', 'times', name='times'),
    url(r'^notification/$', 'notify', name='notification'),
    url(r'^notification/(?P<notify_id>[\d]+)/delete/$', 'notify_del', name='notify_del'),
)

#city
urlpatterns += patterns('djclub.app.views.city',
	url(r'^city/([\w\-\d]+)/?$', 'show'),
)

#timesystem
urlpatterns += patterns('djclub.app.views.timesystem',
	url(r'^bank/?$', 'bank'),
)

#reply
urlpatterns += patterns('djclub.app.views.reply',
    url(r'^topic/(?P<topic_id>[\d]+)/reply/$', 'reply_add', name='replyadd'),
    url(r'^reply/(?P<reply_id>[\d]+)/thanks/$', 'thanks', name='thanks'),
    url(r'^reply/(?P<reply_id>[\d]+)/delete/$', 'reply_del', name='replydel'),
    url(r'^reply/(?P<reply_id>[\d]+)/edit/$', 'reply_edit', name='replyedit'),
)

#overtime
urlpatterns += patterns('djclub.app.views.overtime',
    url(r'^ot/add/', 'record'),
    url(r'^ot/show/', 'index'),

    url(r'^animetop/', 'animeTop'),
    url(r'^showdown/', 'showdown'),
)

djclub/app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models

class Bank(models.Model):
    time = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_bank'

class City(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True)
    site = models.CharField(unique=True, max_length=150, blank=True)
    description = models.TextField(blank=True)
    class Meta:
        db_table = u'djclub_city'

class User(models.Model):
    name = models.CharField(unique=True, max_length=150)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    time = models.IntegerField(null=True, blank=True)
    timeswitch = models.IntegerField(null=True, blank=True, default=1)
    topswitch = models.IntegerField(null=True, blank=True, default=1)
    emailswitch = models.IntegerField(null=True, blank=True, default=1)
    timetop = models.IntegerField(null=True, blank=True)
    usercenter = models.CharField(unique=True, max_length=150, blank=True)
    status = models.IntegerField(null=True, blank=True)
    steam_id = models.IntegerField(null=True, blank=True)
    description = models.TextField(blank=True)
    website = models.TextField(blank=True)
    date = models.IntegerField(null=True, blank=True)
    city = models.ForeignKey(City, null=True, blank=True)
    class Meta:
        db_table = u'djclub_user'
        
    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/member/%s" % self.name

class Nodeclass(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True)
    description = models.TextField(blank=True)
    status = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_nodeclass'

    def __unicode__(self):
        return self.name

class Node(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True)
    site = models.CharField(unique=True, max_length=150, blank=True)
    description = models.TextField(null=True, blank=True)
    nodeclass = models.ForeignKey(Nodeclass, null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    date = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_node'

    def __unicode__(self):
        return self.name

class Topic(models.Model):
    author = models.ForeignKey(User, null=True, blank=True)
    title = models.CharField(max_length=240, blank=True)
    text = models.TextField(blank=True)
    node = models.ForeignKey(Node, null=True, blank=True)
    vote = models.IntegerField(null=True, blank=True, default=0)
    report = models.IntegerField(null=True, blank=True)
    date = models.IntegerField(null=True, blank=True)
    last_reply_date = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_topic'

class Reads(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    topic = models.ForeignKey(Topic, null=True, blank=True)
    class Meta:
        db_table = u'djclub_reads'


class Votes(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    topic = models.ForeignKey(Topic, null=True, blank=True)
    class Meta:
        db_table = u'djclub_votes'

class Reply(models.Model):
    topic = models.ForeignKey(Topic, null=True, blank=True)
    author = models.ForeignKey(User, null=True, blank=True)
    text = models.TextField(blank=True)
    date = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_reply'

class Bill(models.Model):
    author = models.ForeignKey(User, null=True, blank=True)
    topic = models.ForeignKey(Topic, null=True, blank=True)
    reply = models.ForeignKey(Reply, null=True, blank=True)
    user_id = models.IntegerField(null=True, blank=True)
    time = models.IntegerField(null=True, blank=True)
    balance = models.IntegerField(null=True, blank=True)
    type = models.IntegerField(null=True, blank=True)
    date = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_bill'

class Favorites(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    topic = models.ForeignKey(Topic, null=True, blank=True)
    class Meta:
        db_table = u'djclub_favorites'


class Thanks(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    reply = models.ForeignKey(Reply, null=True, blank=True)
    class Meta:
        db_table = u'djclub_thanks'

class Notify(models.Model):
    author = models.ForeignKey(User, null=True, blank=True)
    status = models.IntegerField(null=True, blank=True, default=0)
    topic = models.ForeignKey(Topic, null=True, blank=True)
    reply = models.ForeignKey(Reply, null=True, blank=True)
    type = models.IntegerField(null=True, blank=True)
    date = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'djclub_notify'

class Overtime(models.Model):
    who = models.ForeignKey(User, null=True, blank=True)
    record_time = models.IntegerField(null=True, blank=True)
    remark = models.TextField(blank=True)

    class Meta:
        db_table = u'djclub_overtime'

djclub/app/forms.py
# coding: utf-8
from django import forms

from djclub.app.models import User, Node, Favorites, Reply, Votes, Reads, Thanks
from djclub.app.functions import check_password as cp

class LoginForm(forms.Form):
	username = forms.CharField(max_length=30, min_length=4)
	password = forms.CharField(widget=forms.PasswordInput(render_value=True), min_length=6)

	def check_password(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		try:
			if '@' in username:
				user = User.objects.get(email=username)
			else:
				user = User.objects.get(name=username)
			self.user = user
			self.user.favorites = []
			for fav in Favorites.objects.filter(user=user):
				self.user.favorites.append(int(fav.topic_id))
			#self.user.reads = []
			#for read in Reads.objects.filter(user=user):
			#	self.user.reads.append(int(read.topic_id))
			self.user.votes = []
			for vote in  Votes.objects.filter(user=user):
				self.user.votes.append(int(vote.topic_id))
			self.user.thanks = []
			for thank in Thanks.objects.filter(user=user):
				self.user.thanks.append(int(thank.reply_id))
			return cp(password, user.password)
		except Exception, e:
			print e
			raise User.DoesNotExist("The username does not exists!")
			

class RegisterForm(forms.Form):
	username = forms.CharField(max_length=30, min_length=4)
	email = forms.EmailField(max_length=75)
	password1 = forms.CharField(widget=forms.PasswordInput(render_value=True), min_length=6)
	password2 = forms.CharField(widget=forms.PasswordInput(render_value=True), min_length=6)

	def clean_password2(self):
		password1 = self.cleaned_data['password1']
		password2 = self.cleaned_data['password2']

		if password1 != password2:
			raise forms.ValidationError("The two passwords you typed do not match")
		return password2

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			user = User.objects.get(name=username)
		except Exception, e:
			return username
		if user:
			raise forms.ValidationError("The username already exists!")
		
	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			user = User.objects.get(email=email)
		except Exception, e:
			return email
		if user:
			raise forms.ValidationError("The email already exists!")


class SettingForm(forms.Form):
	EXTRA_CHOICES_OPENCLOSE = [('1', '开'),('0', '关'),]
	EXTRA_CHOICES_YESNO = [('1', '是'),('0', '否'),]

	username = forms.CharField(max_length=30, min_length=4)
	email = forms.EmailField(max_length=75)
	emailswitch = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}), choices=EXTRA_CHOICES_OPENCLOSE)
	timeswitch = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}), choices=EXTRA_CHOICES_OPENCLOSE)
	topswitch = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}), choices=EXTRA_CHOICES_YESNO)
	website = forms.URLField(required=False)
	description = forms.CharField(widget=forms.Textarea(attrs={'class':'span3'}), required=False)
	city = forms.CharField(max_length=100, min_length=2, required=False)
	password = forms.CharField(widget=forms.PasswordInput(render_value=True), min_length=6, required=False)

	def clean_username(self):
		username = self.cleaned_data['username']
		user = None
		if username == getattr(self.user, 'name', ''):
			return username
		try:
			user = User.objects.get(name=username)
		except Exception, e:
			return username
		if user:
			raise forms.ValidationError("The username already exists!")
		
	def clean_email(self):
		email = self.cleaned_data['email']
		user = None
		if email == getattr(self.user, 'email', ''):
			return email
		try:
			user = User.objects.get(email=email)
		except Exception, e:
			return email
		if user:
			raise forms.ValidationError("The email already exists!")

	def check_password(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		try:
			user = User.objects.get(name=username)
			return cp(password, user.password)
		except Exception, e:
			raise User.DoesNotExist("The username does not exists!")


class NodeForm(forms.Form):
	EXTRA_CHOICES_DISPLAYHIDDEN = [('1', '显示'), ('0', '隐藏'),]

	name = forms.CharField(max_length=50)
	site = forms.CharField(max_length=50)
	description = forms.CharField(widget=forms.Textarea(attrs={'class':'span3'}), required=False)
	nodeclass =forms.CharField(max_length=50)
	status = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}), choices=EXTRA_CHOICES_DISPLAYHIDDEN)
	site = forms.CharField(max_length=50)

	def clean_name(self):
		name = self.cleaned_data['name']
		node = None
		if name == getattr(self.node, 'name', ''):
			return name
		try:
			node = Node.objects.get(name=name)
		except Exception, e:
			return name
		if node:
			raise forms.ValidationError("The node's name already exists!")

	def clean_site(self):
		site = self.cleaned_data['site']
		nodesite = None
		if site == getattr(self.node, 'site', ''):
			return site
		try:
			nodesite = Node.objects.get(site=site)
		except Exception, e:
			return site
		if nodesite:
			raise forms.ValidationError("The node's site already exists!")


class TopicForm(forms.Form):
	title = forms.CharField(max_length=240, min_length=2)
	text = forms.CharField(widget=forms.Textarea(attrs={'class':'span3', 'rows':'20', 'cols':'40'}))
	nodename = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}), choices=[])

	def __init__(self, *args, **kwargs):
		super(TopicForm, self).__init__(*args, **kwargs)
		choices_nodes = [('0', '选择节点'),]
		nodes = Node.objects.all()
		for n in nodes:
			choices_nodes.append((str(n.id), n.name))
		self.fields['nodename'].choices = choices_nodes
		#print choices_nodes

	def clean_nodename(self):
		nodename = self.cleaned_data['nodename']
		if int(nodename) == 0:
			raise forms.ValidationError("必须选择节点")
		return nodename

class ReplyForm(forms.Form):
	content = forms.CharField(widget=forms.Textarea(attrs={'rows':'7', 'cols':'40'}))

djclub/app/views/city.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from djclub.app.models import City

def show(request, name=''):
	users = {}
	city = {}
	try:
		city = City.objects.get(name=name)
		users = city.user_set.all()
	except Exception, e:
		print 'city.show:', e
	return render_to_response('city_view.html', {'users':users, 'city':city}, context_instance=RequestContext(request))

djclub/app/views/overtime.py
# coding: utf-8
import time, datetime

from django.shortcuts import render_to_response, redirect
from django.contrib import messages
from django.template import RequestContext
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from djclub.app.models import Node, Nodeclass, Topic, User, Reply, Favorites, Bank, Bill, Votes, Overtime
from djclub.app.forms import TopicForm, ReplyForm
from djclub.app.functions import getTimeZone, send_mail, AnimeParser, VoteParser, mycmp

def index(request):
	if not request.session.get('user'):
		messages.info(request, '登录后进行操作!')
		return redirect('login')
	ot = Overtime.objects.filter(who=request.session['user']).order_by('-record_time')

	page = request.GET.get('page', 1)
	paginator = Paginator(ot, settings.PER_PAGE)
	page_obj = None
	try:
		page_obj = paginator.page(page)
	except PageNotAnInteger:
		page_obj = paginator.page(1)
	except EmptyPage:
		page_obj = paginator.page(paginator.num_pages)
	return render_to_response('overtime.html', locals(), context_instance=RequestContext(request))

def animeTop(request):
	import urllib2, re
	from math import fsum

	index_page = r'http://www.dm123.cn/data/2013/201304'
	vote_page = r'http://www.dm123.cn/e/public/vote/?classid=2358&id='
	html = urllib2.urlopen(index_page).read()
	p = AnimeParser()
	p.parse(html)
	p.close()
	links = p.links
	rc = re.compile(r'.*/2013-\d{2}-\d{2}/(\d+).html')
	ids = []
	for link in links:
		values = rc.findall(link,re.I)
		if values:
			ids.extend(values)
	ids = list(set(ids))
	kv = {}
	for id in ids:
		html = urllib2.urlopen(vote_page + id).read()
		vp = VoteParser()
		vp.parse(html)
		vp.close()
		title = vp.title
		vs = vp.votes
		s = int(fsum(vs))
		vs.append(s)
		if title:
			kv[title] = vs
		vp = None
		#print kv
	kv = sorted(kv.items(), cmp=mycmp)
	print kv
	return render_to_response('animetop.html', locals(), context_instance=RequestContext(request))

def showdown(request):
	return render_to_response('showdown.html', locals(), context_instance=RequestContext(request))

def record(request):
	who = request.GET.get('who', 'solu')
	key = request.GET.get('key', '')
	remark = request.GET.get('remark', '')

	import hashlib
	mykey = hashlib.md5(settings.SECRET_KEY + who).hexdigest()

	if (key == mykey):
		user = None
		try:
			user = User.objects.get(name=who)
		except Exception, e:
			print e
			return redirect('/')
		
		ot = Overtime(who=user,record_time=int(time.time()), remark=remark)
		ot.save()
		
		#本月加班次数
		today = datetime.date.today()
		timeZone = getTimeZone(today)

		count = user.overtime_set.filter(record_time__gte=timeZone['st']) \
								 .filter(record_time__lte=timeZone['et']).count()

		#print count
		message = "%s年%s月%s日加班累计%s次。" % (timeZone['year'], timeZone['month'],today.day, count)
		send_mail('每月加班次数统计', message, user.email)
	return redirect('/')

djclub/templates/_page.html
{% load djclub_filter %}
<nav class=pagination>
	<ul>
		{% if page_obj.number > 4 %}
			{% if page_obj.number|toadd:2 < page_obj.paginator.num_pages %}
				{% if page_obj.has_previous %}
					<li class=prev>
						<a rel=prev href="?page={{ page_obj.previous_page_number }}">上一页</a>
					</li>
				{% endif %}
				<li>
					<a href="?page=1">1</a>
				</li>
				<li class=disabled>
					<a href="#">...</a>
				</li>
				{% with page_obj.number|tosub:3 as x %}
				{% with page_obj.number|toadd:2 as y %}
				{% for i in x|myrange:y %}
					{% if i|toadd:1 == page_obj.number %}
						<li class=active>
					{% else %}
						<li>
					{% endif %}
							<a href="?page={{ i|toadd:1 }}">{{ i|toadd:1 }}</a>
						</li>
				{% endfor %}
				{% endwith %}
				{% endwith %}
				<li class=disabled>
					<a href="#">...</a>
				</li>
				<li>
					<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
				</li>
				{% if page_obj.has_next %}
					<li class=next>
						<a rel=next href="?page={{ page_obj.next_page_number }}">下一页</a>
					</li>
				{% endif %}
			{% else %}
				{% if page_obj.has_previous %}
					<li class=prev>
						<a rel=prev href="?page={{ page_obj.previous_page_number }}">上一页</a>
					</li>
				{% endif %}
				<li>
					<a href="?page=1">1</a>
				</li>
				<li class=disabled>
					<a href="#">...</a>
				</li>
				{% with page_obj.number|tosub:3 as x %}
				{% with page_obj.paginator.num_pages as y %}
				{% for i in x|myrange:y %}
					{% if i|toadd:1 == page_obj.number %}
						<li class=active>
					{% else %}
						<li>
					{% endif %}
							<a href="?page={{ i|toadd:1 }}">{{ i|toadd:1 }}</a>
						</li>
				{% endfor %}
				{% endwith %}
				{% endwith %}
				{% if page_obj.has_next %}
					<li class=next>
						<a rel=next href="?page={{ page_obj.next_page_number }}">下一页</a>
					</li>
				{% endif %}
			{% endif %}
		{% else %}
			{% if page_obj.paginator.num_pages <= 4 %}
				{% for i in 0|myrange:page_obj.paginator.num_pages %}
					{% if i|toadd:1 == page_obj.number %}
						<li class=active>
					{% else %}
						<li>
					{% endif %}
							<a href="?page={{ i|toadd:1 }}">{{ i|toadd:1 }}</a>
						</li>
				{% endfor %}
			{% else %}
				{% if page_obj.number|toadd:2 < page_obj.paginator.num_pages %}
					{% if page_obj.has_previous %}
						<li class=prev>
							<a rel=prev href="?page={{ page_obj.previous_page_number }}">上一页</a>
						</li>
					{% endif %}
					{% with page_obj.number|add:2 as x%}
					{% for i in 0|myrange:x %}
						{% if i|toadd:1 == page_obj.number %}
							<li class=active>
						{% else %}
							<li>
						{% endif %}
								<a href="?page={{ i|toadd:1 }}">{{ i|toadd:1 }}</a>
							</li>
					{% endfor %}
					{% endwith %}
							<li class=disabled>
								<a href="#">...</a>
							</li>
							<li>
								<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
							</li>
							{% if page_obj.has_next %}
								<li class=next>
									<a rel=next href="?page={{ page_obj.next_page_number }}">下一页</a>
								</li>
							{% endif %}
				{% else %}
					{% if page_obj.has_previous %}
						<li class=prev>
							<a rel=prev href="?page={{ page_obj.previous_page_number }}">上一页</a>
						</li>
					{% endif %}
					<li>
						<a href="?page=1">1</a>
					</li>
					<li class=disabled>
						<a href="#">...</a>
					</li>
					{% with page_obj.number|tosub:2 as x %}
					{% with page_obj.paginator.num_pages as y %}
					{% for i in x|myrange:y %}
						{% if i|toadd:1 == page_obj.number %}
							<li class=active>
						{% else %}
							<li>
						{% endif %}
								<a href="?page={{ i|toadd:1 }}">{{ i|toadd:1 }}</a>
							</li>
					{% endfor %}
					{% endwith %}
					{% endwith %}
					{% if page_obj.has_next %}
						<li class=next>
							<a rel=next href="?page={{ page_obj.next_page_number }}">下一页</a>
						</li>
					{% endif %}
				{% endif %}
			{% endif %}
		{% endif %}
	</ul>
</nav>

djclub/templates/_topiclist.html
{% load djclub_filter %}
<section id=topics class="box no-padding">
	<table class=item-list>
		<tbody>
			{% for topic in page_obj.object_list %}
				<tr id=topic-{{ topic.id }}>
					<td class=avatar>
						<a href="/member/{{ topic.author.name }}/">
							<img src="{{ topic.author.email|gravatar:64 }}">
						</a>
					</td>
					<td>
						<h3>
							<a href="{% url topicview topic.id %}">{{ topic.title }}</a>
						</h3>
						<div class=info>
							<span class=tags>
								<a href="/node/{{ topic.node.site }}/">{{ topic.node.name }}</a>
							</span>
							<span class=author>
								<a href="/member/{{ topic.author.name }}/">{{ topic.author.name }}</a>
							</span>
							<span class=time>
								创建于 {{ topic.date|format_datetime }}
								{% if topic.reply_set.all.count %}
										，<a href="/member/{{ topic.id|get_topic_last_reply_id|get_reply_author_id|get_user_info:'name' }}/">{{ topic.id|get_topic_last_reply_id|get_reply_author_id|get_user_info:'name' }}</a>
										回复于 {{ topic.id|get_topic_last_reply_id|get_reply_date|format_datetime }}
								{% endif %}
							</span>
						</div>
					</td>
					<td class="reply-count last">
						{% if topic.id|get_topic_reply_count %}
							<a href="{% url topicview topic.id %}" class=read>{{ topic.id|get_topic_reply_count }}</a>
						{% else %}
							<a href="{% url topicview topic.id %}">{{ topic.id|get_topic_reply_count }}</a>
						{% endif %}
					</td>
					{% if request.session.user.id == 1 %}
						<td><p align="right"><a onclick="return confirm('你确认要删除该主题？');" href="{% url topicdel topic.id %}">删除</a></p>
						</td>
					{% endif %}
				</tr>
			{% endfor %}
		</tbody>
	</table>
</section>

djclub/templates/topic_add.html
{% extends "layout.html" %}
{% block title %}创建主题 › {{ node.name }}{% endblock %}
{% block sidebarin %}{% endblock %}
{% load djclub_filter %}
{% load markup %}
{% block breadcrumb %}<li>创建主题{% endblock %}
{% block body %}
<style type="text/css">
#id_title {width:450px;}
#id_text {width: 450px;}
</style>
	{% if request.session.user %}
		<div id=mainbar class=span9>
			<section class=box>
				<form action="{% url topicadd %}" method="post" class="new_topic">
					{% csrf_token %}
					<legend>创建主题<span class="gray little" style="float: right;"><a href="javascript:void(function(){var%20d%20=%20document,a%20=%20'setAttribute',s%20=%20d.createElement('script');s[a]('tyle','text/javascript');s[a]('src','http://weibotuchuang.sinaapp.com/bookmark.js');d.head.appendChild(s);})();">Add Image</a></span></legend>
					<div class=form-horizontal>
						<div class=control-group>
							<label class=control-label>标题：</label>
							<div class=controls>
								{{ form.title }}
							</div>
						</div>
						<div class=control-group>
							<label class=control-label>正文：</label>
							<div class=controls>
								{{ form.text }}
							</div>
						</div>
						<div class=control-group>
							<label class=control-label>节点：</label>
							<div class=controls>
								{{ form.nodename }}
							</div>
						</div>
						<div class=form-actions>
							<input class="btn btn-primary" type=submit value=果断提交 name=commit>
						</div>
					</div>
				</form>
			</section>
		</div>
	{% endif %}
{% endblock %}

djclub/templates/topic_edit.html
{% extends "layout.html" %}
{% load djclub_filter %}
{% block title %}主题编辑 › {{ topic.node.name }}{% endblock %}
{% block sidebarin %}{% endblock %}
{% block breadcrumb %}<li><a href="/node/{{ topic.node.site }}">{{ topic.node.name }}</a>{% endblock %}
{% block body %}
<style type="text/css">
#id_title {width:450px;}
#id_text {width: 450px;}
</style>
	{% if request.session.user %}
		<div id=mainbar class=span9>
			<section class=box>
				<form action="{% url topicedit topic.id %}" method=post class=new_topic>
					{% csrf_token %}
					<legend>主题编辑</legend>
					<div class=form-horizontal>
						<div class=control-group>
							<label class=control-label>标题：</label>
							<div class=controls>
								{{ form.title }}
							</div>
						</div>
						<div class=control-group>
							<label class=control-label>正文：</label>
							<div class=controls>
								{{ form.text }}
							</div>
						</div>
						<div class=control-group>
							<label class=control-label>节点：</label>
							<div class=controls>
								{{ form.nodename }}
							</div>
						</div>
						<div class=form-actions>
							<input class="btn btn-primary" type=submit value=果断提交 name=commit>
						</div>
					</div>
				</form>
			</section>
		</div>
	{% endif %}
{% endblock %}